require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Ml::ListsController, type: :controller do
  include Devise::TestHelpers

  # This should return the minimal set of attributes required to create a valid
  # Ml::List. As you add validations to Ml::List, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Ml::ListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ml_lists as @ml_lists" do
      list = Ml::List.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:ml_lists)).to eq([list])
    end
  end

  describe "GET #show" do
    it "assigns the requested ml_list as @ml_list" do
      list = Ml::List.create! valid_attributes
      get :show, params: {id: list.to_param}, session: valid_session
      expect(assigns(:ml_list)).to eq(list)
    end
  end

  describe "GET #new" do
    it "assigns a new ml_list as @ml_list" do
      get :new, params: {}, session: valid_session
      expect(assigns(:ml_list)).to be_a_new(Ml::List)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ml_list as @ml_list" do
      list = Ml::List.create! valid_attributes
      get :edit, params: {id: list.to_param}, session: valid_session
      expect(assigns(:ml_list)).to eq(list)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Ml::List" do
        expect {
          post :create, params: {ml_list: valid_attributes}, session: valid_session
        }.to change(Ml::List, :count).by(1)
      end

      it "assigns a newly created ml_list as @ml_list" do
        post :create, params: {ml_list: valid_attributes}, session: valid_session
        expect(assigns(:ml_list)).to be_a(Ml::List)
        expect(assigns(:ml_list)).to be_persisted
      end

      it "redirects to the created ml_list" do
        post :create, params: {ml_list: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Ml::List.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ml_list as @ml_list" do
        post :create, params: {ml_list: invalid_attributes}, session: valid_session
        expect(assigns(:ml_list)).to be_a_new(Ml::List)
      end

      it "re-renders the 'new' template" do
        post :create, params: {ml_list: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ml_list" do
        list = Ml::List.create! valid_attributes
        put :update, params: {id: list.to_param, ml_list: new_attributes}, session: valid_session
        list.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ml_list as @ml_list" do
        list = Ml::List.create! valid_attributes
        put :update, params: {id: list.to_param, ml_list: valid_attributes}, session: valid_session
        expect(assigns(:ml_list)).to eq(list)
      end

      it "redirects to the ml_list" do
        list = Ml::List.create! valid_attributes
        put :update, params: {id: list.to_param, ml_list: valid_attributes}, session: valid_session
        expect(response).to redirect_to(list)
      end
    end

    context "with invalid params" do
      it "assigns the ml_list as @ml_list" do
        list = Ml::List.create! valid_attributes
        put :update, params: {id: list.to_param, ml_list: invalid_attributes}, session: valid_session
        expect(assigns(:ml_list)).to eq(list)
      end

      it "re-renders the 'edit' template" do
        list = Ml::List.create! valid_attributes
        put :update, params: {id: list.to_param, ml_list: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ml_list" do
      list = Ml::List.create! valid_attributes
      expect {
        delete :destroy, params: {id: list.to_param}, session: valid_session
      }.to change(Ml::List, :count).by(-1)
    end

    it "redirects to the ml_lists list" do
      list = Ml::List.create! valid_attributes
      delete :destroy, params: {id: list.to_param}, session: valid_session
      expect(response).to redirect_to(ml_lists_url)
    end
  end

  describe "GET #join" do

    let!(:list) { FactoryGirl.create(:ml_list)}
    let(:current_user) { FactoryGirl.create(:user_with_addresses, is_gadz: true)}
    let(:target_user) { current_user}

    it_behaves_like "a logged users only endpoint", :get, :join , {list_id:1, user_id: 1}

    context "logged user" do

      before(:each) do
        sign_in current_user
      end

      context "An allowed lists" do

        let!(:list) { FactoryGirl.create(:ml_list,inscription_policy: "open")}

        before(:each) do
          xhr :get, :join, {list_id:list.id, user_id: target_user.id, format: :js}
        end

        it {is_expected.to respond_with :success }
        it "add user to list members" do
          skip ("Problème avec Rabbit MQ à régler #ToDo")
          expect(list.members).to include(target_user)
        end
      end

      context "Not an allowed lists" do
        let!(:list) { FactoryGirl.create(:ml_list,inscription_policy: "closed")}

        before(:each) do
          xhr :get, :join, {list_id:list.id, user_id: target_user.id, format: :js}
        end
        it {is_expected.to respond_with :forbidden }
      end

      context "A lists already joined" do
      end
    end
  end
end
